# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='obrazek'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='reserver',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='osoba_rezerwująca'),
        ),
    ]
