# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20160721_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/', verbose_name='obrazek'),
        ),
    ]
