# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_auto_20160804_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'prezent', 'verbose_name_plural': 'prezenty'},
        ),
    ]
