# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_auto_20160804_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='obrazek'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='reserver',
            field=models.CharField(max_length=200, null=True, verbose_name='osoba_rezerwująca'),
        ),
    ]
