# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='children_number',
            new_name='childrens_number',
        ),
    ]
