# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20160729_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'verbose_name': 'potwierdzenie'},
        ),
    ]
