# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100, verbose_name='imię_panny')),
                ('bride_last_name', models.CharField(max_length=100, verbose_name='nazwisko_panny')),
                ('groom_name', models.CharField(max_length=100, verbose_name='imię_kawalera')),
                ('groom_last_name', models.CharField(max_length=100, verbose_name='nazwisko_kawalera')),
            ],
        ),
    ]
