# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0002_couple'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='address',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='address',
            field=models.CharField(default='asdawsdq', max_length=200),
            preserve_default=False,
        ),
    ]
