# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0003_auto_20160729_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_login_required', models.BooleanField(default=True)),
            ],
        ),
    ]
