# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0004_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='if_login_required',
            new_name='login_required',
        ),
    ]
