# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0005_auto_20160804_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'konfiguracja'},
        ),
        migrations.AlterModelOptions(
            name='couple',
            options={'verbose_name': 'para młoda'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'wesele'},
        ),
        migrations.AlterModelOptions(
            name='wedding',
            options={'verbose_name': 'ślub'},
        ),
        migrations.AlterField(
            model_name='configuration',
            name='login_required',
            field=models.BooleanField(default=True, verbose_name='logowanie'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='bride_last_name',
            field=models.CharField(default='Smith', max_length=100, verbose_name='nazwisko_panny'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='bride_name',
            field=models.CharField(default='Bride', max_length=100, verbose_name='imię_panny'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='groom_last_name',
            field=models.CharField(default='Smith', max_length=100, verbose_name='nazwisko_kawalera'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='groom_name',
            field=models.CharField(default='Groom', max_length=100, verbose_name='imię_kawalera'),
        ),
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.CharField(default='plac Defilad, Warszawa', max_length=200, verbose_name='adres'),
        ),
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.CharField(default='Party description', max_length=1000, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='obrazek'),
        ),
        migrations.AlterField(
            model_name='party',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 40, 41, 716838), verbose_name='kiedy'),
        ),
        migrations.AlterField(
            model_name='party',
            name='where',
            field=models.CharField(default='Party place', max_length=200, verbose_name='sala'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='address',
            field=models.CharField(default='plac Defilad, Warszawa', max_length=200, verbose_name='adres'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='description',
            field=models.CharField(default='Wedding description', max_length=1000, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='obrazek'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 40, 41, 716387), verbose_name='kiedy'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='where',
            field=models.CharField(default='Wedding place', max_length=200, verbose_name='kościół'),
        ),
    ]
