# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0006_auto_20160804_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'konfiguracja', 'verbose_name_plural': 'konfiguracja'},
        ),
        migrations.AlterModelOptions(
            name='couple',
            options={'verbose_name': 'para młoda', 'verbose_name_plural': 'para młoda'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'wesele', 'verbose_name_plural': 'wesele'},
        ),
        migrations.AlterModelOptions(
            name='wedding',
            options={'verbose_name': 'ślub', 'verbose_name_plural': 'ślub'},
        ),
        migrations.AlterField(
            model_name='party',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 43, 32, 664668), verbose_name='kiedy'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 43, 32, 664150), verbose_name='kiedy'),
        ),
    ]
