# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0007_auto_20160804_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 49, 5, 852794), verbose_name='kiedy'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 49, 5, 852346), verbose_name='kiedy'),
        ),
    ]
