# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0008_auto_20160804_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 13, 45, 29, 761137), verbose_name='kiedy'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 13, 45, 29, 760382), verbose_name='kiedy'),
        ),
    ]
