# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0009_auto_20160806_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 14, 34, 25, 750562), verbose_name='kiedy'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 14, 34, 25, 749774), verbose_name='kiedy'),
        ),
    ]
